INFO:root:127.0.0.1
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:root:2022-07-04 07:21:23.272892:127.0.0.1
ERROR:root:2022-07-04 07:21:50.906938:127.0.0.1:User1:Hash1
ERROR:root:2022-07-04 07:22:19.053655:127.0.0.1:User1:hash
ERROR:root:2022-07-04 07:21:50.906938:127.0.0.1:User1:Hash1
ERROR:root:2022-07-04 07:22:53.384715:127.0.0.1:User1:hash ERROR:root:2022-07-04 07:21:50.906938:127.0.0.1:User1:Hash1
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
ERROR:root:2022-07-04 07:33:40.803427:127.0.0.1:User1
ERROR:root:2022-07-04 07:33:56.077580:127.0.0.1:User1 \nuser2
INFO:root:2022-07-04 07:45:55.218505:127.0.0.1
INFO:root:2022-07-04 07:48:54.794168:127.0.0.1
INFO:root:2022-07-04 07:49:48.437612:127.0.0.1
INFO:root:2022-07-04 07:49:50.548011:127.0.0.1
INFO:root:2022-07-04 07:50:15.676492:127.0.0.1
INFO:root:2022-07-04 07:50:39.003232:127.0.0.1
INFO:root:2022-07-04 07:50:48.264349:127.0.0.1
INFO:root:2022-07-04 07:51:29.216251:127.0.0.1
INFO:root:2022-07-04 07:51:34.019034:127.0.0.1
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /ssrf_lab2 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /login/ HTTP/1.1" 200 17092
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /ssrf_target HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /login/ HTTP/1.1" 200 17092
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /ssrf_target HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /login/ HTTP/1.1" 200 17092
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /ssrf_target HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /login/ HTTP/1.1" 200 17092
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /ssrf_target HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /login/ HTTP/1.1" 200 17092
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /ssrf_target HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /login/ HTTP/1.1" 200 17092
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /ssrf_target HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /login/ HTTP/1.1" 200 17092
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /ssrf_lab2 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /login/ HTTP/1.1" 200 17092
WARNING:django.security.csrf:Forbidden (CSRF token from POST incorrect.): /ssrf_lab2
WARNING:django.request:Not Found: /favicon.ico
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /ssrf_lab2 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /login/ HTTP/1.1" 200 17092
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.112.128:80
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.youtube.com:443
DEBUG:urllib3.connectionpool:https://www.youtube.com:443 "GET /watch?v=ynImA_neDfQ HTTP/1.1" 200 None
ERROR:django.request:Internal Server Error: /mitre/3
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py", line 62, in function
    return func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/mitre.py", line 21, in mitre_top3
    return render(request, 'mitre/mitre_top3.html')
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: mitre/mitre_top3.html
ERROR:django.request:Internal Server Error: /mitre/25
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py", line 62, in function
    return func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/mitre.py", line 136, in mitre_top25
    return render(request, 'mitre/mitre_top25.html')
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/template/engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/template/engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/template/base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 28: 'endblock'. Did you forget to register or load this tag?
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/mitre.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/mitre.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/mitre.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/mitre.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/mitre.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/mitre.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/mitre.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/mitre.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/mitre.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/mitre.py changed, reloading.
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /xss_challenge/
Traceback (most recent call last):
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py", line 97, in xss_challenge
    template = loader.get_template('xss_challenge.html')
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: xss_challenge.html
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /xss_challenge/
Traceback (most recent call last):
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py", line 97, in xss_challenge
    template = loader.get_template('xss_challenge.html')
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: xss_challenge.html
ERROR:django.request:Internal Server Error: /xss_challenge/
Traceback (most recent call last):
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py", line 97, in xss_challenge
    template = loader.get_template('xss_challenge.html')
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: xss_challenge.html
ERROR:django.request:Internal Server Error: /xss_challenge/
Traceback (most recent call last):
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py", line 97, in xss_challenge
    template = loader.get_template('xss_challenge.html')
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: xss_challenge.html
ERROR:django.request:Internal Server Error: /xss_challenge/
Traceback (most recent call last):
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py", line 97, in xss_challenge
    template = loader.get_template('xss_challenge.html')
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: xss_challenge.html
ERROR:django.request:Internal Server Error: /xss_challenge/
Traceback (most recent call last):
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py", line 97, in xss_challenge
    template = loader.get_template('xss_challenge.html')
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: xss_challenge.html
ERROR:django.request:Internal Server Error: /xss_challenge/
Traceback (most recent call last):
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py", line 97, in xss_challenge
    template = loader.get_template('xss_challenge.html')
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: xss_challenge.html
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/urls.py changed, reloading.
ERROR:django.request:Internal Server Error: /xss_challenge/
Traceback (most recent call last):
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py", line 97, in xss_challenge
    template = loader.get_template('xss_challenge.html')
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: xss_challenge.html
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /xss_challenge/
Traceback (most recent call last):
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py", line 98, in xss_challenge
    return render(request, 'Lab/XSS/xss_challenge.html', context)
UnboundLocalError: local variable 'context' referenced before assignment
ERROR:django.request:Internal Server Error: /xss_challenge/
Traceback (most recent call last):
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py", line 98, in xss_challenge
    return render(request, 'Lab/XSS/xss_challenge.html', context)
UnboundLocalError: local variable 'context' referenced before assignment
ERROR:django.request:Internal Server Error: /xss_challenge/
Traceback (most recent call last):
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py", line 98, in xss_challenge
    return render(request, 'Lab/XSS/xss_challenge.html', context)
UnboundLocalError: local variable 'context' referenced before assignment
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
WARNING:django.request:Not Found: /xss_challenge/xss_challenge
WARNING:django.request:Not Found: /xss_challenge/xss_challenge
WARNING:django.request:Not Found: /xss_challenge/xss_challenge
WARNING:django.request:Not Found: /xss_challenge/xss_challenge
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
WARNING:django.request:Not Found: /xss_challenge/
WARNING:django.request:Not Found: /xss_challenge/
WARNING:django.request:Not Found: /xss_challenge/
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
WARNING:django.request:Not Found: /xss_challenge/
WARNING:django.request:Not Found: /xss_challenge/
WARNING:django.request:Not Found: /xss_challenge/
WARNING:django.request:Not Found: /xss_challenge/
WARNING:django.request:Not Found: /xss_challenge/
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
WARNING:django.request:Not Found: /xss_challenge/
WARNING:django.request:Not Found: /xss_challenge/
WARNING:django.request:Not Found: /xss_challenge/
WARNING:django.request:Not Found: /xss_challenge/
WARNING:django.request:Not Found: /xss_challenge/
WARNING:django.request:Not Found: /xss_challenge/
WARNING:django.request:Not Found: /xss_challenge/
WARNING:django.request:Not Found: /xss_challenge/
WARNING:django.request:Not Found: /xss/
WARNING:django.request:Not Found: /xss_challenge/
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
WARNING:django.request:Not Found: /xss_challenge/
WARNING:django.request:Not Found: /xss_challenge/
WARNING:django.request:Not Found: /xss_challenge/
WARNING:django.request:Not Found: /xss_challenge/
WARNING:django.request:Not Found: /xss_challenge/
WARNING:django.request:Not Found: /xss_challenge/
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /xss_challenge
Traceback (most recent call last):
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py", line 97, in xss_challenge
    return render(request, 'Lab/XSS/xss_challenge.html', context)
UnboundLocalError: local variable 'context' referenced before assignment
ERROR:django.request:Internal Server Error: /xss_challenge
Traceback (most recent call last):
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py", line 97, in xss_challenge
    return render(request, 'Lab/XSS/xss_challenge.html', context)
UnboundLocalError: local variable 'context' referenced before assignment
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
WARNING:django.request:Not Found: /xss_challenge/
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
WARNING:django.request:Not Found: /xss_challenge/
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/urls.py changed, reloading.
WARNING:django.request:Not Found: /xss_challenge/xss.js
WARNING:django.request:Not Found: /xss_challenge/xss.js
WARNING:django.request:Not Found: /xss_challenge/xss.js
WARNING:django.request:Not Found: /xss_challenge/Lab/XSS/xss.js
WARNING:django.request:Not Found: /xss_challenge/xss.js
WARNING:django.request:Not Found: /xss_challenge/xss.js
WARNING:django.request:Not Found: /xss_challenge/xss.js
WARNING:django.request:Not Found: /xss_challenge/xss.js
ERROR:django.request:Internal Server Error: /xss_challenge/
Traceback (most recent call last):
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py", line 99, in xss_challenge
    return render(request, 'Lab/XSS/xss_challenge.html', context)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 7: 'static', expected 'endblock'. Did you forget to register or load this tag?
ERROR:django.request:Internal Server Error: /xss_challenge/
Traceback (most recent call last):
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py", line 99, in xss_challenge
    return render(request, 'Lab/XSS/xss_challenge.html', context)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 7: 'static', expected 'endblock'. Did you forget to register or load this tag?
WARNING:django.request:Not Found: /a6
ERROR:django.request:Internal Server Error: /xss_challenge
Traceback (most recent call last):
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/middleware/common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/xss_challenge/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR:django.request:Internal Server Error: /xss_challenge
Traceback (most recent call last):
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/middleware/common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/xss_challenge/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/urls.py changed, reloading.
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /xss_challenge
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /xss_challenge
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/pygoat/settings.py changed, reloading.
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /xss_challenge
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /xss_challenge
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /xss_challenge
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /xss_challenge
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /xss_challenge
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /xss_challenge
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /xss_challenge
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /xss_challenge
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /xss_challenge
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/pygoat/settings.py changed, reloading.
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /xss_challenge
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/pygoat/settings.py changed, reloading.
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /xss_challenge
ERROR:django.request:Internal Server Error: /xss_challenge
Traceback (most recent call last):
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/toxin/Project/gsoc/pygoat/pygoat/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view introduction.views.xss_challenge didn't return an HttpResponse object. It returned None instead.
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /xss_challenge
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /xss_challenge
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /xss_challenge
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /xss_challenge
WARNING:django.request:Not Found: /xss_challenge/
WARNING:django.request:Not Found: /xss_challenge/
WARNING:django.request:Not Found: /xss_challenge/
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
WARNING:django.request:Not Found: /x
WARNING:django.request:Not Found: /x
WARNING:django.request:Not Found: /x
WARNING:django.request:Not Found: /x
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/introduction/urls.py changed, reloading.
WARNING:django.request:Not Found: /xss_challenge
WARNING:django.request:Not Found: /xss_challenge
WARNING:django.request:Not Found: /xss_challenge
WARNING:django.request:Not Found: /xss_challenge
WARNING:django.request:Not Found: /xss_lab2
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /xss_lab2
WARNING:django.request:Not Found: /xss_lab2
WARNING:django.request:Not Found: /xss_lab2
WARNING:django.request:Not Found: /xss_challenge
WARNING:django.request:Not Found: /xss_lab2
WARNING:django.request:Not Found: /x
WARNING:django.request:Not Found: /x
WARNING:django.request:Not Found: /x
WARNING:django.request:Not Found: /x
WARNING:django.request:Not Found: /x
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/introduction/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /register
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/toxin/Project/gsoc/pygoat/introduction/views.py", line 67, in register
    return render(request, 'registration/register.html', {'form': form})
UnboundLocalError: local variable 'form' referenced before assignment
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/introduction/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /register
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/toxin/Project/gsoc/pygoat/introduction/views.py", line 62, in register
    form.save()
AttributeError: 'RegistrationForm' object has no attribute 'save'
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/introduction/views.py changed, reloading.
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /introduction/home.html
WARNING:django.request:Not Found: /introduction/home.html/
WARNING:django.request:Not Found: /introduction/home.html/
WARNING:django.request:Not Found: /introduction/home.html
WARNING:django.request:Not Found: /introduction/homepage
WARNING:django.request:Not Found: /introduction/
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/introduction/views.py changed, reloading.
WARNING:django.request:Not Found: /introduction/
WARNING:django.request:Not Found: /introduction/home.html
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/introduction/forms.py changed, reloading.
WARNING:django.security.csrf:Forbidden (CSRF token missing or incorrect.): /admin/auth/user/
ERROR:django.request:Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/template/base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/template/base.py", line 742, in resolve
    new_obj = func(obj, *arg_vals)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/crispy_forms/templatetags/crispy_forms_filters.py", line 58, in as_crispy_form
    template = uni_form_template(template_pack)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/crispy_forms/templatetags/crispy_forms_filters.py", line 21, in uni_form_template
    return get_template("%s/uni_form.html" % template_pack)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: bootstrap4/uni_form.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: bootstrap4/uni_form.html
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /cryptographic_failure/lab3/Admin/admin
WARNING:django.request:Not Found: /cryptographic_failure/lab3/Admin/
WARNING:django.request:Not Found: /cryptographic_failure/lab3/admin
WARNING:django.request:Not Found: /x
WARNING:django.request:Not Found: /x
WARNING:django.request:Not Found: /x
WARNING:django.request:Not Found: /x
WARNING:django.request:Not Found: /x
WARNING:django.request:Not Found: /x
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/urls.py changed, reloading.
ERROR:django.request:Internal Server Error: /xssL3
Traceback (most recent call last):
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view introduction.views.xss_lab3 didn't return an HttpResponse object. It returned None instead.
ERROR:django.request:Internal Server Error: /xssL3
Traceback (most recent call last):
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view introduction.views.xss_lab3 didn't return an HttpResponse object. It returned None instead.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /xssL3
Traceback (most recent call last):
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py", line 124, in xss_lab3
    result = re.sub(pattern, '', username)
  File "/usr/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
ERROR:django.request:Internal Server Error: /xssL3
Traceback (most recent call last):
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py", line 124, in xss_lab3
    result = re.sub(pattern, '', username)
  File "/usr/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /xssL3
Traceback (most recent call last):
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py", line 124, in xss_lab3
    result = re.sub(pattern, '', username)
  File "/usr/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /xssL3
Traceback (most recent call last):
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py", line 125, in xss_lab3
    result = re.sub(pattern, '', username)
  File "/usr/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /xssL3
Traceback (most recent call last):
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py", line 125, in xss_lab3
    result = re.sub(pattern, '', username)
  File "/usr/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
ERROR:django.request:Internal Server Error: /xssL3
Traceback (most recent call last):
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py", line 125, in xss_lab3
    result = re.sub(pattern, '', username)
  File "/usr/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
ERROR:django.request:Internal Server Error: /xssL3
Traceback (most recent call last):
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/sankalpa/Desktop/gsoc/myenv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py", line 125, in xss_lab3
    result = re.sub(pattern, '', username)
  File "/usr/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/sankalpa/Desktop/gsoc/pygoat/introduction/views.py changed, reloading.
WARNING:django.request:Not Found: /mitre/21f
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/settings.py changed, reloading.
WARNING:django.request:Not Found: /mitre/21f
INFO:django.utils.autoreload:/home/toxin/Project/gsoc/pygoat/pygoat/settings.py changed, reloading.
WARNING:django.request:Not Found: /mitre/21f
WARNING:django.request:Not Found: /x
